language: rust

rust:
- stable
- beta
- nightly
- 1.18.0

matrix:
  allow_failures:
    - rust: nightly

sudo: required

addons:
  apt:
    packages:
    - postfix

before_script:
  - smtp-sink 2525 1000&
  - sudo chgrp -R postdrop /var/spool/postfix/maildrop

script:
  - cargo test --verbose --all

