baseURL = "http://docs.lettre.at/"
languageCode = "en-us"
title = "Lettre site"
theme = "hugo-theme-learn"
publishDir = "../docs"
PygmentsCodeFences = true

[params]
  editURL = "https://github.com/lettre/lettre/edit/master/website/content/"
  description = "Documentation for the Lettre mailer in Rust"
  author = "Alexis Mousset"
  autoNav = true
  search = true
